"""create users and responses

Revision ID: 7fd906b02759
Revises:
Create Date: 2024-09-28 14:35:58.993976+03:00

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = '7fd906b02759'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Adding stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_table(
        'responses',
        sa.Column('id', sa.Integer(), primary_key=False, autoincrement=True),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.String(), nullable=False),
        sa.Column('time', sa.String(), nullable=False),
        sa.Column('tokens', sa.Integer(), nullable=False),
        sa.Column('duration', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
        sqlite_autoincrement=True,
    )
    op.create_index(
        op.f('ix_responses_user_id'),
        'responses',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Removing stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_responses_user_id'), table_name='responses')
    op.drop_table('responses')
    op.drop_table('users')
    # ### end Alembic commands ###
