"""create contexts

Revision ID: 5db00320dfe4
Revises: 7fd906b02759
Create Date: 2024-09-28 15:38:02.509652+03:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5db00320dfe4'
down_revision: Union[str, None] = '7fd906b02759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Adding stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'contexts',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('context', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('user_id'),
    )
    op.create_index(
        op.f('ix_contexts_user_id'),
        'contexts',
        ['user_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Removing stuff."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contexts_user_id'), table_name='contexts')
    op.drop_table('contexts')
    # ### end Alembic commands ###
